### PR TITLE
feat: add info about Schibsted

### PR DESCRIPTION
**Pull request by michaldomagalski**
Related to: https://github.com/copotrzebne-pl/copotrzebne-frontend/issues/183

### CODE REVIEW

**Comment by baqui** [comment]
image

Looks imho

**Comment by agnieszkalasyk** [comment]
We could perhaps add more info "about us" - something like "Copotrzebne.pl (change name depending on the site name) is a charity app powered by Schibsted Tech Polska. (....)

I am also missing some "air" below Schibsted logo, at least on my small screen
Screen Shot 2022-05-09 at 13 37 52
"

We could consider adding "powered by" here too, apart from copyrights:
Screen Shot 2022-05-09 at 13 38 02

I was wondering if we could add a small Sch logo next to Open Cracow Coallition one?
Screen Shot 2022-05-09 at 13 41 26

Let me know what you think @michaldomagalski @baqui :)

**Comment by baqui** [comment]
@AgaLasyk 
- adjusted about us text to include schoibsted in description
- added spacing to schibsted logo in about us page
- added: Powered by <schibsted logo> in copyright

> I was wondering if we could add a small Sch logo next to Open Cracow Coallition one?

There is no enough space to place that logo there.

**Comment by baqui** [comment]
As we changed PR flow, I'm closing this PR and creating a new one to develop branch

**Pull request closed without merging**
